/**
 * Forge Constraint Library
 * 
 * Documents known Forge mistake patterns and their correct counterparts.
 * Each constraint is sourced from a specific Jira story where the mistake was first observed.
 * 
 * Used to generate explicit instructions in the Forge system prompt to prevent recurring errors.
 */

export interface ForgeConstraint {
  pattern: string;
  constraint: string;
  source: string;
}

/**
 * Known constraint patterns from production execution failures.
 * Add new constraints as single array entries - no other changes required.
 */
export const forgeConstraints: ForgeConstraint[] = [
  {
    pattern: "executionId in CreateExecutionInput",
    constraint: "executionId must never appear in a CreateExecutionInput object literal - it is generated by the database",
    source: "ORKY-48"
  },
  {
    pattern: "executionRepository.updateStatus()",
    constraint: "executionRepository.updateState() is the correct method name - updateStatus() does not exist",
    source: "ORKY-48"
  },
  {
    pattern: "Missing ExecutionRepository methods",
    constraint: "failIfNotTerminal(), releaseLock(), acquireLock(), hasActiveOrCompletedExecution() DO exist on ExecutionRepository - never omit them or rename them",
    source: "ORKY-48"
  },
  {
    pattern: "BatchExecution field casing",
    constraint: "BatchExecution fields use camelCase: storyIds, epicId, status - never snake_case",
    source: "ORKY-48"
  },
  {
    pattern: "SQL parameter syntax",
    constraint: "All SQL parameters use $1/$2 positional syntax - never named parameters",
    source: "system rule"
  },
  {
    pattern: "Database pool access",
    constraint: "getPool() is the only way to access the database pool - never new Pool()",
    source: "system rule"
  }
];

/**
 * Builds a formatted constraint block for injection into the Forge system prompt.
 * Returns a numbered list of all constraints with their sources.
 * 
 * @returns Formatted constraint block as string
 */
export function buildConstraintBlock(): string {
  const header = "## Known Constraint Patterns (Never Violate)\n\n";
  const constraints = forgeConstraints
    .map((c, index) => `${index + 1}. **${c.pattern}**: ${c.constraint} (Source: ${c.source})`)
    .join("\n");
  return header + constraints;
}
